# permissions for end users to view geolocators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: geolocator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: geolocator-viewer-role
rules:
- apiGroups:
  - apps.suse.com
  resources:
  - geolocators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.suse.com
  resources:
  - geolocators/status
  verbs:
  - get
