---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.suse.com
  resources:
  - geolocators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.suse.com
  resources:
  - geolocators/finalizers
  verbs:
  - update
- apiGroups:
  - apps.suse.com
  resources:
  - geolocators/status
  verbs:
  - get
  - patch
  - update
